### ISSUE TITLE
TypeError: Cannot read property 'windowsazure' of undefined

### ISSUE THREAD

**Issue by georgeedwards** [PeterStaev/nativescript-azure-mobile-apps#6]
I have been working with the plugin for a while and all of a sudden, the error below has appeared, causing my app to crash. I don't think it is because of something in my app necessarily, as when I revert to a previously working version from my source control, the same issue shows. Any idea what's causing this?

```
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
Fail to load module: /data/data/org.nativescript.AzureTest/files/app/main.js

TypeError: Cannot read property 'windowsazure' of undefined
File: "<unknown>, line: 1, column: 265

StackTrace: 
    Frame: function:'', file:'/data/data/org.nativescript.AzureTest/files/app/tns_modules/nativescript-azure-mobile-apps/client/client.js', line: 24, column: 98
    Frame: function:'require', file:'', line: 1, column: 266
    Frame: function:'', file:'/data/data/org.nativescript.AzureTest/files/app/Components/Home/home.component.js', line: 8, column: 16
    Frame: function:'require', file:'', line: 1, column: 266
    Frame: function:'', file:'/data/data/org.nativescript.AzureTest/files/app/app.component.js', line: 5, column: 24
    Frame: function:'require', file:'', line: 1, column: 266
    Frame: function:'', file:'/data/data/org.nativescript.AzureTest/files/app/main.js', line: 4, column: 23
    Frame: function:'require', 
```

It looks like the issue line is: `client.android.js`:

> nativeAuthenticationProviders[user_1.AuthenticationProvider.AzureActiveDirectory] = com.microsoft.windowsazure.mobileservices.authentication.MobileServiceAuthenticationProvider.WindowsAzureActiveDirectory;
